# Quarkus configuration
quarkus.http.port=8080

# Redis L2 Cache Configuration
quarkus.cache.type=redis
quarkus.cache.redis.price-cache.expire-after-write=60s

# Redis connection
quarkus.redis.hosts=redis://127.0.0.1:6379

# ScyllaDB (via Cassandra Client)
quarkus.cassandra.contact-points=127.0.0.1:9042
quarkus.cassandra.local-datacenter=datacenter1
quarkus.cassandra.keyspace=pricing
quarkus.cassandra.init.eager-init=true
quarkus.cassandra.init.connection.timeout=20s

# Monitoramento
quarkus.micrometer.export.prometheus.enabled=true
quarkus.micrometer.export.prometheus.path=/metrics
quarkus.smallrye-health.root-path=/health
quarkus.native.cleanup-server=true
quarkus.native.enable-reports=true
