version: '3.8'

services:
  scylla:
    image: scylladb/scylla:latest
    container_name: scylla
    ports:
      - "9042:9042"
      - "19042:19042"
    volumes:
      - ./scripts/init-scylla.cql:/init.cql
    command: --smp 1 --memory 512M --overprovisioned 1 --developer-mode 1

  scylla-init:
    image: scylladb/scylla:latest
    container_name: scylla-init
    depends_on:
      - scylla
    volumes:
      - ./scripts/init-scylla.cql:/init.cql
    entrypoint: ["sh", "-c", "until cqlsh scylla 9042 -f /init.cql; do echo 'Aguardando ScyllaDB...'; sleep 5; done"]

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
