{
 "title": "Clearing - Key Metrics",
 "refresh": "15s",
 "panels": [
  {
   "title": "Process CPU Usage",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 6 },
   "targets": [
    { "expr": "process_cpu_usage", "legendFormat": "cpu" }
   ]
  },
  {
   "title": "JVM Heap %",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 6 },
   "targets": [
    {
     "expr": "(sum(jvm_memory_used_bytes{area=\"heap\"}) / sum(jvm_memory_max_bytes{area=\"heap\"}))*100",
     "legendFormat": "heap %"
    }
   ]
  },
  {
   "title": "JVM Threads Live",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 6, "w": 12, "h": 6 },
   "targets": [
    { "expr": "jvm_threads_live", "legendFormat": "threads" }
   ]
  },
  {
   "title": "Req/s - /accounts/transfer (1m)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 6, "w": 12, "h": 6 },
   "targets": [
    {
     "expr": "increase(http_server_requests_seconds_count{uri=\"/accounts/transfer\"}[1m])",
     "legendFormat": "req/s"
    }
   ]
  },
  {
   "title": "Latency (avg) - /accounts/transfer (5m)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 12, "w": 12, "h": 6 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{uri=\"/accounts/transfer\"}[5m]) / rate(http_server_requests_seconds_count{uri=\"/accounts/transfer\"}[5m])",
     "legendFormat": "avg latency"
    }
   ]
  },
  {
   "title": "Hikari Active Connections",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 12, "w": 12, "h": 6 },
   "targets": [
    {
     "expr": "hikaricp_connections_active{pool=\"HikariPoolClearing\"}",
     "legendFormat": "active"
    }
   ]
  }
 ]
}