### Enviar Notificação via Email
POST http://localhost:8080/notify
Content-Type: application/json

{
  "recipient": "dev@exemplo.com",
  "content": "Sua fatura de Março/2026 já está disponível para pagamento.",
  "channelType": "EMAIL"
}

### Enviar Notificação via SMS
POST http://localhost:8080/notify
Content-Type: application/json

{
  "recipient": "+5511999998888",
  "content": "Seu código de verificação é: 482931",
  "channelType": "SMS"
}

### Enviar Notificação via Push
POST http://localhost:8080/notify
Content-Type: application/json

{
  "recipient": "device_token_fcm_123456",
  "content": "Você recebeu uma nova mensagem de @vini0410",
  "channelType": "PUSH"
}

### Testar Canal Inválido (Erro)
POST http://localhost:8080/notify
Content-Type: application/json

{
  "recipient": "teste",
  "content": "Erro esperado",
  "channelType": "WHATSAPP"
}
