# MongoDB Configuration
 quarkus.mongodb.connection-string=mongodb+srv://CrudTestUser:6gAGbDkwNoWcPRnQ@crudtest.xed1svd.mongodb.net/KtlCrudTestDB?appName=CrudTest
 quarkus.mongodb.database=quarkuscrud
